// <auto-generated />
using System;
using HikingApp_RSWEB.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HikingApp_RSWEB.Migrations
{
    [DbContext(typeof(HikingApp_RSWEBContext))]
    [Migration("20210609012209_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("HikingApp_RSWEB.Models.Planinar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Ime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prezime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfilePicture")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Vozrast")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Planinar");
                });

            modelBuilder.Entity("HikingApp_RSWEB.Models.Rezervacii", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("PlaninarId")
                        .HasColumnType("int");

                    b.Property<int>("TuraId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PlaninarId");

                    b.HasIndex("TuraId");

                    b.ToTable("Rezervacii");
                });

            modelBuilder.Entity("HikingApp_RSWEB.Models.Tura", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DatumKraj")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DatumPocetok")
                        .HasColumnType("datetime2");

                    b.Property<int?>("FirstVodichId")
                        .HasColumnType("int");

                    b.Property<string>("Mesto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SecoundVodichId")
                        .HasColumnType("int");

                    b.Property<string>("Tezina")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Vremetraenje")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FirstVodichId");

                    b.HasIndex("SecoundVodichId");

                    b.ToTable("Tura");
                });

            modelBuilder.Entity("HikingApp_RSWEB.Models.Vodich", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Ime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pozicija")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prezime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfilePicture")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Vozrast")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Vodich");
                });

            modelBuilder.Entity("HikingApp_RSWEB.Models.Rezervacii", b =>
                {
                    b.HasOne("HikingApp_RSWEB.Models.Planinar", "Planinar")
                        .WithMany("Turi")
                        .HasForeignKey("PlaninarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HikingApp_RSWEB.Models.Tura", "Tura")
                        .WithMany("Planinari")
                        .HasForeignKey("TuraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HikingApp_RSWEB.Models.Tura", b =>
                {
                    b.HasOne("HikingApp_RSWEB.Models.Vodich", "FirstVodich")
                        .WithMany("Tura1")
                        .HasForeignKey("FirstVodichId");

                    b.HasOne("HikingApp_RSWEB.Models.Vodich", "SecoundVodich")
                        .WithMany("Tura2")
                        .HasForeignKey("SecoundVodichId");
                });
#pragma warning restore 612, 618
        }
    }
}
